### ISSUE TITLE
Add images for Shattered Web

### ISSUE THREAD

**Issue by vidhanio** [BeepFelix/CSGO---Discord-RichEmbed#12]
Add image assets for all the new shattered web maps

**Comment by BeepIsla** [comment]
Ah yes, I forgot about that, will do that right now.

**Comment by BeepIsla** [comment]
Finished with the new map images 63748a8.

There are also new icons for Coop Strike and Guardian mode which I still have to find in the game files.

**Comment by BeepIsla** [comment]
Alright found them 7a530f9.
