### ISSUE TITLE
Always in main menu

### ISSUE THREAD

**Issue by Roki100** [BeepFelix/CSGO---Discord-RichEmbed#15]
When i am starting this rpc, everything works fine but when im joining game like comp, discord status always shows im in main menu, is this a bug or issue only im having?
i am not using lobby thing with api key

**Comment by BeepIsla** [comment]
Did you move `gamestate_integration_discord.cfg` into your config folder? Do not rename it either.

**Comment by Roki100** [comment]
![image](https://user-images.githubusercontent.com/35699619/72685580-c5e3fd00-3aeb-11ea-9f9a-8b50955b5f75.png)
my folder looks like this so i think yes?
unless you mean creating `config` folder

**Comment by BeepIsla** [comment]
No, you have to copy and paste the `gamestate_integration_discord.cfg`  file into your CSGO directory. `<Steam>/common/Counter-Strike: Global Offensive/cfg`

**Comment by Roki100** [comment]
okay it works, sorry for not reading readme fully
