### ISSUE TITLE
Broken RegEx causes UnhandledPromiseRejectionWarning (Process.js, line 51)

### ISSUE THREAD

**Issue by syntacsdev** [BeepFelix/CSGO---Discord-RichEmbed#16]
Hey there.

After setting up your program and running it, I was given an `UnhandledPromiseRejectionWarning` every ten seconds, which mentioned an `Invalid regular expression`.

The invalid expression is on line 51 of `Process.js`:
`let match = line.trim().match(/^(?<process>.+\.exe)\s+(?<pid>\d+)\s+(.+)\s+(\d+)\s+(\d+([\.,�\s]\d+|){0,})\s+[A-Z]+$/);`

**Comment by BeepIsla** [comment]
Update NodeJS
