### ISSUE TITLE
when you do " pm2 start index.js --name "CSGO RichPresence" "

### ISSUE THREAD

**Issue by Karo1ina** [BeepFelix/CSGO---Discord-RichEmbed#17]
when you do pm2 start index.js --name "CSGO RichPresence" it saids status stopped any way to fix that here is an example
![powershell_vjGAdiq82o](https://user-images.githubusercontent.com/64229258/84477292-4cf66500-ac87-11ea-9f2e-8875df98b95a.png)

**Comment by BeepIsla** [comment]
Any errors in `pm2 logs "CSGO RichPresence" --lines 200`

**Comment by Karo1ina** [comment]
![powershell_fSCtCk3rVS](https://user-images.githubusercontent.com/64229258/84566937-0f6c0780-ad6d-11ea-94cc-fdd2fba819db.png)
ok now ?

**Comment by BeepIsla** [comment]
Did you do `npm install`? There are modules missing which should be installed.

**Comment by Karo1ina** [comment]
i did and it didnt work now it just decided to work fully like what

**Comment by BeepIsla** [comment]
I just assume you executed it in the wrong folder the first time, whatever as you said it works now so all good.
