### ISSUE TITLE
Still Working?

### ISSUE THREAD

**Issue by MikWhoo** [BeepFelix/CSGO---Discord-RichEmbed#18]
Is this still working or should we do something to make it work again?

**Comment by BeepIsla** [comment]
Still works just not updated

**Comment by MikWhoo** [comment]
Do i have to change something?

**Comment by BeepIsla** [comment]
Did you try reading the README? You can use it without changing anything or you can adjust it

**Comment by MikWhoo** [comment]
Lul tossic very much

**Comment by MikWhoo** [comment]
Got an error that say that it cant get token

**Comment by BeepIsla** [comment]
Screenshot the error
