### ISSUE TITLE
[HELP] Assets doesn't work.

### ISSUE THREAD

**Issue by XdekHckr** [BeepFelix/CSGO---Discord-RichEmbed#20]
I changed assets in assets\other\menu.png
but it's still old default menu.png even after reinstalling in new folder and restarting pc...
Any idea why?

**Comment by BeepIsla** [comment]
Assets are not stored on your PC. They are uploaded to Discord. If you want to change the images to your own ones you must create [a Discord Application](https://github.com/BeepIsla/CSGO---Discord-RichPresence#custom-discord-application) and put its client ID into your config.

**Comment by XdekHckr** [comment]
ahh i missed that, thanks
