### ISSUE TITLE
asset issues

### ISSUE THREAD

**Issue by gentuwu** [BeepFelix/CSGO---Discord-RichEmbed#21]
When I join a game, my assets stop showing on discord. Any idea why? I use discord canary btw.

**Comment by BeepIsla** [comment]
If you use [a custom Discord Application](https://github.com/BeepIsla/CSGO---Discord-RichPresence#custom-discord-application) then it may be due to invalid implementation, otherwise it could be simply because this hasn't been updated in a while with any of the new maps.

**Comment by gentuwu** [comment]
> If you use [a custom Discord Application](https://github.com/BeepIsla/CSGO---Discord-RichPresence#custom-discord-application) then it may be due to invalid implementation, otherwise it could be simply because this hasn't been updated in a while with any of the new maps.

Yeah, I use a custom application.

**Comment by BeepIsla** [comment]
Probably missing images then, make sure to always have a `random` image for when a map-image does not exist, it will fall back to that.

**Comment by gentuwu** [comment]
ohhh... im stupid. i wanna have a logo always show for my large image, should i just upload a random.png then? does the software need the files to be nsmed correctly when you use a custom app?

**Comment by BeepIsla** [comment]
If you always want one and the same image to show then just use an asset named `random`. Names must match exactly for the application to work.

Essentially what happens is when the rich presence starts it fetches a list of available assets, if you are playing on a map like `de_dust2` it checks with the fetched list of assets if such an image exists, if it does it will use that, if it does not exist the rich presence will fallback to the `random` asset. If the `random` asset doesn't exist then it might not show anything, I don't quite know.

**Comment by gentuwu** [comment]
tyvm! <3
