### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by uku3lig** [BeepFelix/CSGO---Discord-RichEmbed#22]
I made a fix which allows support for linux, on [my fork](https://github.com/uku3lig/CSGO---Discord-RichPresence/tree/linux). Tested only on Arch Linux.

I'll make a pull request when i'm done, I still want to add automatic platform detection.

**Comment by BeepIsla** [comment]
I have read your message before you edited it and at the time simply decided to copy/paste your changes into my local version instead of creating a "Linux" branch. I just have to push it to master and it should be done and working.

**Comment by uku3lig** [comment]
I just created a pull request, you can check if it suits what you want.
