### ISSUE TITLE
update.js issue

### ISSUE THREAD

**Issue by ZoniBoy00** [BeepFelix/CSGO---Discord-RichEmbed#25]
i get this error code: C:\Users\jonis\OneDrive\Työpöytä\CSGO---Discord-RichPresence-master\CSGO---Discord-RichPresence-master\dev>node update
Found 92 maps
Processing ar_baggage (1/92)
(node:4736) UnhandledPromiseRejectionWarning: HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (C:\Users\jonis\OneDrive\Työpöytä\CSGO---Discord-RichPresence-master\CSGO---Discord-RichPresence-master\node_modules\got\dist\source\as-promise\index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:4736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BeepIsla** [comment]
You don't have to run the updater unless you use your own Discord application for this. As mentioned throughout the README, you can simply use mine by defining my `clientID`

**Comment by ZoniBoy00** [comment]
how do i then make the maps appear on the discord?

**Comment by BeepIsla** [comment]
As I said, just use my Discord Application.

In your config in the `clientID` field, you just leave it default (`"561657394292195331"`), that's all you have to do.

**Comment by ZoniBoy00** [comment]
ok
