### ISSUE TITLE
[SUGGESTION] Change the application name to CS:GO

### ISSUE THREAD

**Issue by Retr0-01** [BeepFelix/CSGO---Discord-RichEmbed#28]
If I remember correctly, the rich presence application name is taken from the registered developer application itself, the one that uses the ID in the config file.

Reason I suggest this change is that the current name (fully typed CS:GO) is cut out while viewing a member in the members list or while previewing their profile.

**Comment by qualk** [comment]
Or add that option to the config.

**Comment by BeepIsla** [comment]
This can't be a config thing because it relies on the how the Discord Application is named, so the only way you can customize it is if you make your own Discord Application with your own images. Personally I prefer it the way it is with the full written name.

**Comment by Retr0-01** [comment]
Yeah I figured out that it is based on the Discord application name and I personally like the short type (CS:GO) because it doesn't get cut out so I went ahead and created my own application. Would recommend anyone else to do the same if they want to.

Closing this.
