### ISSUE TITLE
Unable to add custom maps to discord

### ISSUE THREAD

**Issue by vidhanio** [BeepFelix/CSGO---Discord-RichEmbed#5]
When trying to create my own app and adding workshop maps, the discord developer portal throws an error:
`String value did not match validation regex. (name)`
![image](https://user-images.githubusercontent.com/41439633/65772810-fea93200-e108-11e9-9b67-e5f968fdddea.png)
I think that this is because there are slashes in the asset name. Is it possible to create a new naming scheme for this?

**Comment by BeepIsla** [comment]
Yes ofcourse, I will check which characters are allowed and come up with something today. I'll update you once its done.

**Comment by BeepIsla** [comment]
I have added name normalization 3c89fad318bf6fcd8f541196abd98e6d78a24d57, replace every non normal character (`A-Z` `0-9`) with an underscore (`_`) and it should work. Refer to README for more info.

Report back if everything works fine.

**Comment by vidhanio** [comment]
Works perfectly now, thanks!
![image](https://i.imgur.com/tAKZnIE.png)
