### ISSUE TITLE
Spectating other team in casual when dead causes team to switch

### ISSUE THREAD

**Issue by vidhanio** [BeepFelix/CSGO---Discord-RichEmbed#7]
When you die in casual, you can spectate any player you want, and when spectating an enemy player, the rich presence detects it as your team switching, and the small image switches, along with the hover text.

**Comment by BeepIsla** [comment]
There is nothing I can do against this, the game state integration only tells us information about the user we are currently spectating and not about anyone else unless we are actually spectator, being dead does not count.
